#!/bin/env python

##################################################################################################################
# Name:        dpw (decode password)                                                                             #
# Author:      Randy Johnson                                                                                     #
# Description: Decodes a UU encoded string.                                                                      #
#                                                                                                                #
# History:                                                                                                       #
#                                                                                                                #
# Date       Ver. Who              Change Description                                                            #
# ---------- ---- ---------------- ----------------------------------------------------------------------------- #
# 07/06/2012 1.00 Randy Johnson    Initial release.                                                              #
# 09/19/2012 2.00 Randy Johnson    Corrections to Usage (removed -v) and improved error handling                 #
# 12/07/2012 2.10 Randy Johnson    Changed encode/decode to use built-in string functions.                       #
# 07/17/2015 3.00 Randy Johnson    Updated for Python 2.4-3.4 compatibility.                                     #
# 07/13/2017 3.01 Randy Johnson    Added program description to Usage.                                           #
##################################################################################################################


# --------------------------------------
# ---- Import Python Modules -----------
# --------------------------------------
from optparse     import OptionParser
from os.path      import basename
from sys          import exit
from sys          import argv
from sys          import version_info

# ------------------------------------------------
# Imports that are conditional on Python Version.
# ------------------------------------------------
if (version_info[0] >= 3):
  from base64 import b64decode
# ------------------------------------------------  


# --------------------------------------
# ---- Main Program --------------------
# --------------------------------------
if (__name__ == '__main__'):
  Cmd            = basename(argv[0]).split('.')[0]
  CmdDesc        = 'Decode Password'
  Version        = '3.01'
  VersionDate    = 'Thu Jul 13 12:15:38 CDT 2017'
  DevState       = 'Production'
  Banner         = CmdDesc + ': Release ' + Version + ' '  + DevState + '. Last updated: ' + VersionDate
  
  Usage  = '\n\n-------------------------------------------------------------------------------'
  Usage += '\nDecodes a UU encoded string.'
  ArgParser = OptionParser(Usage)

  ArgParser.add_option('--v', dest='ShowVer', action='store_true', default=False, help="print version info.")
  
  # Parse command line arguments
  Options, args = ArgParser.parse_args()
  argc = len(argv)
  
  ShowVer = Options.ShowVer

  if (ShowVer):
    print('\n%s' % Banner)
    exit()
  
  if argc != 2:
    print('\nSpecify an encoded password to decode.')
    exit(1)
  else:
    Password = argv[1]
    try:
      if (version_info[0] >= 3):
        print(b64decode(Password.encode('utf-8')).decode('utf-8'))
      else:
        print(Password.decode('base64','strict'))
    except:
      print("\n  Are you sure the password was properly")
      print("  encoded? Check it with epw and try again.")

# --------------------------------------
# ---- End Main Program ----------------
# --------------------------------------
