#!/bin/env python

#--------------------------------------------------------------------------------------------------#
# Name:   dpw (decode password)                                                                    #
# Author: Randy Johnson                                                                            #
# Descr:  Decodes a UU encoded string.                                                             #
#--------------------------------------------------------------------------------------------------#

# --------------------------------------
# ---- Import Python Modules -----------
# --------------------------------------
from optparse     import OptionParser
from os.path      import basename
from sys          import exit
from sys          import argv
from sys          import version_info

# ------------------------------------------------
# Imports that are conditional on Python Version.
# ------------------------------------------------
if (version_info[0] >= 3):
  from base64 import b64decode
# ------------------------------------------------  


# --------------------------------------
# ---- Main Program --------------------
# --------------------------------------
if (__name__ == '__main__'):
  Cmd            = basename(argv[0]).split('.')[0]
  CmdDesc        = 'Decode Password'
  Version        = '3.02'
  VersionDate    = 'Fri Jul 19 10:12:14 CDT 2019'
  DevState       = 'Production'
  Banner         = CmdDesc + ': Release ' + Version + ' '  + DevState + '. Last updated: ' + VersionDate
  
  Usage  =  '%s [options]'  % Cmd
  Usage += '\n\n%s'         % CmdDesc
  Usage += '\n------------------------------------------------------------------------------'
  Usage += '\nDecode a UU encoded string.'
  ArgParser = OptionParser(Usage)

  ArgParser.add_option('--v', dest='ShowVer', action='store_true', default=False, help="print version info.")
  
  # Parse command line arguments
  Options, args = ArgParser.parse_args()
  argc = len(argv)
  
  ShowVer = Options.ShowVer

  if (ShowVer):
    print('\n%s' % Banner)
    exit()
  
  if argc != 2:
    print('\nSpecify an encoded password to decode.')
    exit(1)
  else:
    Password = argv[1]
    try:
      if (version_info[0] >= 3):
        print(b64decode(Password.encode('utf-8')).decode('utf-8'))
      else:
        print(Password.decode('base64','strict'))
    except:
      print("\n  Are you sure the password was properly")
      print("  encoded? Check it with epw and try again.")

# --------------------------------------
# ---- End Main Program ----------------
# --------------------------------------
