#!/bin/env python

#--------------------------------------------------------------------------------------------------#
# Name:   epw (encode password)                                                                    #
# Author: Randy Johnson                                                                            #
# Descr:  Generate a UU encoded password from a plain-text string.                                 #
#--------------------------------------------------------------------------------------------------#

# --------------------------------------
# ---- Import Python Modules -----------
# --------------------------------------
from optparse     import OptionParser
from os.path      import basename
from sys          import exit
from sys          import argv
from sys          import version_info

# ------------------------------------------------
# Imports that are conditional on Python Version.
# ------------------------------------------------
if (version_info[0] >= 3):
  from base64 import b64encode
# ------------------------------------------------  

# --------------------------------------
# ---- Main Program --------------------
# --------------------------------------
if (__name__ == '__main__'):
  Cmd            = basename(argv[0]).split('.')[0]
  CmdDesc        = 'Encode Password'
  Version        = '3.02'
  VersionDate    = 'Fri Jul 19 10:52:43 CDT 2019'
  DevState       = 'Production'
  Banner         = CmdDesc + ': Release ' + Version + ' '  + DevState + '. Last updated: ' + VersionDate

  # Process command line options
  # ----------------------------------
  Usage  =  '%s [options]'  % Cmd
  Usage += '\n\n%s'         % CmdDesc
  Usage += '\n-------------------------------------------------------------------------------'
  Usage += '\nGenerate a UU encoded password from a plain-text string.'
  ArgParser = OptionParser(Usage)

  ArgParser.add_option('--v', dest='ShowVer', action='store_true', default=False, help="print version info.")
  
  # Parse command line arguments
  Options, args = ArgParser.parse_args()
  argc = len(argv)
  
  ShowVer = Options.ShowVer

  if (ShowVer):
    print('\n%s' % Banner)
    exit()

  if argc != 2:
    print('\nYou must specify a string of characters to encode.')
    exit(1)
  else:
    Password = argv[1]
    if (version_info[0] >= 3):
      print(b64encode(Password.encode('ascii')).decode("utf-8"))
    else:
      print(Password.encode('base64','strict'))

# --------------------------------------
# ---- End Main Program ----------------
# --------------------------------------
